import fs from 'node:fs';
import path from 'node:path';
import https from 'node:https';
import cp from 'node:child_process';
import { SteamLocator, steamLuaService } from './SteamLuaService.js';

export class SteamUnlockerService {
  constructor() {
    this.ostRepo = { owner: 'madoiscool', repo: 'OST-Nightly' };
    this.bstRepo = { owner: 'madoiscool', repo: 'BetterSteamTools' };
  }

  getUnlockerFiles() {
    return ['OpenSteamTool.dll', 'dwmapi.dll', 'xinput1_4.dll', 'opensteamtool.toml'];
  }

  getUnlockerStatus() {
    const status = steamLuaService.getSteamStatus();
    if (!status.isValid || !status.steamPath) {
      return { isInstalled: false, mode: 'None', filesPresent: [], error: 'Steam not found' };
    }

    const filesPresent = this.getUnlockerFiles().filter(file => {
      return fs.existsSync(path.join(status.steamPath, file));
    });

    const isInstalled = filesPresent.includes('OpenSteamTool.dll') || filesPresent.includes('dwmapi.dll');
    return {
      isInstalled,
      mode: isInstalled ? 'OpenSteamTools' : 'None',
      filesPresent,
      steamPath: status.steamPath
    };
  }

  ensureTomlConfig(steamPath) {
    const tomlPath = path.join(steamPath, 'opensteamtool.toml');
    const defaultToml = [
      '# OpenSteamTool Configuration generated by DarkHub Suite',
      '[general]',
      'enabled = true',
      '',
      '[lua]',
      'paths = ["config/stplug-in"]',
      '',
      '[cloud]',
      'enabled = false',
      ''
    ].join('\n');

    try {
      if (!fs.existsSync(tomlPath)) {
        fs.writeFileSync(tomlPath, defaultToml, 'utf8');
      } else {
        let content = fs.readFileSync(tomlPath, 'utf8');
        if (!content.includes('config/stplug-in')) {
          content += '\n\n[lua]\npaths = ["config/stplug-in"]\n';
          fs.writeFileSync(tomlPath, content, 'utf8');
        }
      }
      return true;
    } catch {
      return false;
    }
  }

  async fetchLatestRelease(owner, repo) {
    return new Promise((resolve, reject) => {
      const url = `https://api.github.com/repos/${owner}/${repo}/releases/latest`;
      const options = {
        headers: {
          'User-Agent': 'DarkHubSuite-Client',
          'Accept': 'application/vnd.github.v3+json'
        }
      };

      https.get(url, options, (res) => {
        if (res.statusCode >= 300 && res.statusCode < 400 && res.headers.location) {
          https.get(res.headers.location, options, (res2) => {
            let body = '';
            res2.on('data', chunk => { body += chunk; });
            res2.on('end', () => {
              try { resolve(JSON.parse(body)); } catch (e) { reject(e); }
            });
          }).on('error', reject);
          return;
        }

        let body = '';
        res.on('data', chunk => { body += chunk; });
        res.on('end', () => {
          try { resolve(JSON.parse(body)); } catch (e) { reject(e); }
        });
      }).on('error', reject);
    });
  }

  async downloadFile(url, destPath) {
    return new Promise((resolve, reject) => {
      const file = fs.createWriteStream(destPath);
      const options = { headers: { 'User-Agent': 'DarkHubSuite-Client' } };

      const get = (targetUrl) => {
        https.get(targetUrl, options, (res) => {
          if (res.statusCode >= 300 && res.statusCode < 400 && res.headers.location) {
            get(res.headers.location);
            return;
          }
          if (res.statusCode !== 200) {
            reject(new Error(`Download failed with status ${res.statusCode}`));
            return;
          }
          res.pipe(file);
          file.on('finish', () => {
            file.close(() => resolve(destPath));
          });
        }).on('error', (err) => {
          try { fs.unlinkSync(destPath); } catch {}
          reject(err);
        });
      };

      get(url);
    });
  }

  extractZipNative(zipPath, destDir) {
    try {
      const escapedZip = zipPath.replace(/'/g, "''");
      const escapedDest = destDir.replace(/'/g, "''");
      const psCommand = `powershell -NoProfile -NonInteractive -Command "Expand-Archive -Force -Path '${escapedZip}' -DestinationPath '${escapedDest}'"`;
      cp.execSync(psCommand, { windowsHide: true });
      return true;
    } catch {
      try {
        cp.execSync(`tar -xf "${zipPath}" -C "${destDir}"`, { windowsHide: true });
        return true;
      } catch (err2) {
        throw new Error(`Failed to extract zip archive: ${err2.message}`);
      }
    }
  }

  async installUnlocker(mode = 'OST') {
    const status = steamLuaService.getSteamStatus();
    if (!status.isValid || !status.steamPath) {
      return { ok: false, error: 'Steam path not detected' };
    }

    const tempZip = path.join(status.steamPath, 'ost_temp.zip');
    try {
      const release = await this.fetchLatestRelease(this.ostRepo.owner, this.ostRepo.repo);
      const zipAsset = release.assets?.find(a => a.name.endsWith('.zip') && a.name.includes('Release'))
                    || release.assets?.find(a => a.name.endsWith('.zip'));

      if (!zipAsset) {
        return { ok: false, error: 'Release ZIP asset not found on GitHub' };
      }

      await this.downloadFile(zipAsset.browser_download_url, tempZip);

      this.extractZipNative(tempZip, status.steamPath);

      this.ensureTomlConfig(status.steamPath);

      try { fs.unlinkSync(tempZip); } catch {}

      return { ok: true, mode: 'OpenSteamTools', version: release.tag_name };
    } catch (err) {
      try { if (fs.existsSync(tempZip)) fs.unlinkSync(tempZip); } catch {}
      return { ok: false, error: err.message };
    }
  }

  async uninstallUnlocker() {
    const status = steamLuaService.getSteamStatus();
    if (!status.isValid || !status.steamPath) {
      return { ok: false, error: 'Steam path not detected' };
    }

    for (const file of this.getUnlockerFiles()) {
      const p = path.join(status.steamPath, file);
      try {
        if (fs.existsSync(p)) fs.unlinkSync(p);
      } catch {}
    }

    return { ok: true };
  }
}

export const steamUnlockerService = new SteamUnlockerService();
